module.exports = {
    name: 'create_checkout_session',
    description: 'Create a checkout session for a product',
    inputSchema: {
        type: 'object',
        properties: {
            tenant_domain: {
                type: 'string',
                description: 'Tenant domain'
            },
            merchant_id: {
                type: 'string',
                description: 'Merchant UUID'
            },
            product_id: {
                type: 'string',
                description: 'Product UUID'
            },
            quantity: {
                type: 'integer',
                description: 'Quantity (default: 1)'
            }
        },
        required: ['tenant_domain', 'merchant_id', 'product_id']
    },

    async execute(args, db) {
        const { tenant_domain, merchant_id, product_id, quantity = 1 } = args;

        // Verify merchant is active
        const merchantResult = await db.query(`
            SELECT m.*, mb.status as billing_status, t.id as tenant_id
            FROM merchants m
            LEFT JOIN merchant_billing mb ON m.id = mb.merchant_id
            JOIN tenants t ON m.tenant_id = t.id
            WHERE t.domain = $1 AND m.id = $2
        `, [tenant_domain, merchant_id]);

        if (merchantResult.rows.length === 0) {
            throw new Error('Merchant not found');
        }

        const merchant = merchantResult.rows[0];

        if (merchant.status !== 'active') {
            throw new Error('Merchant not available');
        }

        if (merchant.billing_status === 'suspended' && !merchant.admin_override) {
            throw new Error('Merchant temporarily unavailable');
        }

        // Get product
        const productResult = await db.query(
            'SELECT * FROM products WHERE id = $1 AND merchant_id = $2',
            [product_id, merchant_id]
        );

        if (productResult.rows.length === 0) {
            throw new Error('Product not found');
        }

        const product = productResult.rows[0];

        if (product.stock_status !== 'in_stock') {
            throw new Error('Product out of stock');
        }

        // For MCP, we return the checkout URL that would be generated by the API
        return {
            content: [
                {
                    type: 'text',
                    text: JSON.stringify({
                        message: 'Use the public API /api/checkout endpoint to create checkout session',
                        product: {
                            id: product.id,
                            name: product.name,
                            price_cents: product.price_cents,
                            currency: product.currency
                        },
                        merchant: {
                            id: merchant.id,
                            domain: merchant.domain
                        }
                    }, null, 2)
                }
            ]
        };
    }
};
